package nesloader.exporter;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import ghidra.app.util.DomainObjectService;
import ghidra.app.util.Option;
import ghidra.app.util.exporter.Exporter;
import ghidra.app.util.exporter.ExporterException;
import ghidra.framework.model.DomainObject;
import ghidra.program.model.address.AddressSetView;
import ghidra.program.model.listing.CodeUnit;
import ghidra.program.model.listing.CodeUnitIterator;
import ghidra.program.model.listing.Listing;
import ghidra.program.model.listing.Program;
import ghidra.program.model.symbol.Symbol;
import ghidra.util.task.TaskMonitor;

/**
 * Exports the disassembled NES program listing as a plain-text assembly file
 * compatible with ca65 / asm6 reassembly workflows.
 *
 * The output includes:
 *   - File header comment with ROM metadata
 *   - Labels from the symbol table
 *   - Disassembled instructions and defined data units
 */
public class NesExporter extends Exporter {

    public NesExporter() {
        super("NES Assembly Listing", "asm", null);
    }

    @Override
    public boolean export(File file, DomainObject domainObject,
                          AddressSetView addressSet, TaskMonitor monitor)
            throws ExporterException, IOException {

        if (!(domainObject instanceof Program program)) {
            log.appendMsg("Domain object is not a Program.");
            return false;
        }

        Listing listing    = program.getListing();
        AddressSetView set = (addressSet != null)
            ? addressSet
            : program.getMemory().getExecuteSet();

        try (PrintWriter writer = new PrintWriter(new FileWriter(file))) {
            writeHeader(writer, program);

            CodeUnitIterator it = listing.getCodeUnits(set, true);
            while (it.hasNext() && !monitor.isCancelled()) {
                CodeUnit cu = it.next();

                String labelLine = buildLabelLine(program, cu);
                if (labelLine != null) {
                    writer.println(labelLine);
                }

                writer.printf("    %s%n", cu.toString());
            }
        }

        return true;
    }

    private void writeHeader(PrintWriter writer, Program program) {
        writer.println("; ============================================================");
        writer.println("; NES Assembly Listing");
        writer.println("; Generated by Ghidra NES Loader Exporter");
        writer.printf ("; Program : %s%n", program.getName());
        writer.printf ("; Language: %s%n", program.getLanguageID());
        writer.println("; ============================================================");
        writer.println();
        writer.println(".cpu \"6502\"");
        writer.println();
    }

    /**
     * Returns "label:" string if any user/analysis symbol exists at this address,
     * null otherwise.
     */
    private String buildLabelLine(Program program, CodeUnit cu) {
        Symbol[] symbols = program.getSymbolTable().getSymbols(cu.getAddress());
        if (symbols.length == 0) return null;
        // Prefer the primary (first) symbol
        return symbols[0].getName() + ":";
    }

    @Override
    public List<Option> getOptions(DomainObjectService domainObjectService) {
        return List.of();
    }

    @Override
    public void setOptions(List<Option> options) {}
}
